grafana:
  adminPassword: admin

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus.kube-system:9090
          access: proxy
          isDefault: true

  service:
    type: ClusterIP
