apiVersion: v2
name: external-dns
description: External DNS for EKS (Route53)
type: application
version: 0.1.0

dependencies:
  - name: external-dns
    version: 1.14.4
    repository: https://kubernetes-sigs.github.io/external-dns/
