#Jenkins shared library file

def call(Map config) {
  pipeline {
    agent {
      kubernetes {
        label "ci-${config.serviceName}"
        defaultContainer 'jnlp'
        yaml """
              apiVersion: v1
              kind: Pod
              spec:
                serviceAccountName: jenkins
                containers:
                - name: jnlp
                  image: jenkins/inbound-agent:4.13-1-jdk17

                - name: kaniko
                  image: gcr.io/kaniko-project/executor:latest
                  command:
                  - /busybox/cat
                  tty: true

                - name: helm
                  image: alpine/helm:3.14.0
                  command:
                  - cat
                  tty: true

                - name: trivy
                  image: ghcr.io/aquasecurity/trivy:latest
                  command:
                  - cat
                  tty: true

                - name: sonar
                  image: sonarsource/sonar-scanner-cli:latest
                  command:
                  - cat
                  tty: true
                """
      }
    }

    environment {
      SERVICE_NAME = config.serviceName
      IMAGE_TAG    = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
      IMAGE_REPO   = "${config.ecrRepo}/${config.serviceName}"
      ENVIRONMENT  = config.environment ?: "dev"
    }


        stages {
            stage('1. Checkout Source Code') {
                steps {
                    cleanWs()
                    checkout scm
                }
            }
            stage('2. SonarQube Code Analysis') {
                when { expression { return config.sonarProjectKey != null } }
                steps {
                    container('sonar') {
                        withCredentials([
                        string(credentialsId: config.sonarCredentialId, variable: 'SONAR_TOKEN')
                        ]) {
                          sh '''
                            sonar-scanner \
                              -Dsonar.projectKey=${config.sonarProjectKey} \
                              -Dsonar.sources=${config.sonarSourcesPath ?: "."} \
                              -Dsonar.host.url=${config.sonarHostUrl} \
                              -Dsonar.login=${SONAR_TOKEN}
                          '''
                    }
                }
            }

                }
            }

            stage('3. Build & Push Image') {
                steps {
                    container('kaniko') {
                      sh '''
                        /kaniko/executor \
                        --dockerfile=${config.dockerfilePath} \
                        --context=. \
                        --destination=${IMAGE_REPO}:${IMAGE_TAG} \
                        --cache=true \
                        --cache-repo=${IMAGE_REPO}-cache
                    '''
                    }
                }
            }

            stage('4. Trivy Vulnerability Scan') {
                  steps {
                    container('trivy') {
                      sh '''
                        trivy image \
                          --cache-dir /tmp/trivy-cache \
                          --exit-code 0 \
                          --severity HIGH,CRITICAL \
                          ${IMAGE_REPO}:${IMAGE_TAG}
                      '''
                    }
                }
            }
            stage('Deploy to Kubernetes') {
                steps {
                    container('helm') {
                        sh '''
                            helm upgrade --install ${SERVICE_NAME} ${config.helmChartPath} \
                            --namespace ${ENVIRONMENT} \
                            --create-namespace \
                            -f ${config.helmChartPath}/values.yaml \
                            -f ${config.helmChartPath}/values-${ENVIRONMENT}.yaml \
                            --set image.repository=${IMAGE_REPO} \
                            --set image.tag=${IMAGE_TAG}
                        '''
                    }
                }
            }

        post {
            success {
                echo "✅ SUCCESS: ${config.serviceName} pipeline complete. Deployed to Kubernetes."
            }
            failure {
                echo "❌ FAILURE: ${config.serviceName} pipeline failed. Check console logs."
            }
        }

        options {
          disableConcurrentBuilds()
          timestamps()
        }
    }
}